services:
  postgres:
    image: postgres:18
    container_name: shipment_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: shipment_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: shipment_rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  shipment:
    build:
      context: .
    container_name: shipment_app
    command: ["/shipment/docker/app.sh"]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "9000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celery:
    build:
      context: .
    container_name: shipment_celery
    command: ["/shipment/docker/celery.sh", "celery"]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/1
      BROKER_REDIS_URL: redis://redis:6379/1
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  flower:
    build:
      context: .
    container_name: shipment_flower
    command: ["/shipment/docker/celery.sh", "flower"]
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/1
      BROKER_REDIS_URL: redis://redis:6379/1
      RMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy