"""typo fix 2

Revision ID: db26b3764c56
Revises: bcd9530f8acc
Create Date: 2026-09-22 10:30:15.637167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db26b3764c56'
down_revision: Union[str, Sequence[str], None] = 'bcd9530f8acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('shipments', 'updated_at_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('updated_at_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.drop_column('shipments', 'updated_at')
    # ### end Alembic commands ###
